USE PRACTICE;

SELECT * FROM MOCK_DATA;

--TOTAL EMPLOYEES

SELECT COUNT(*) AS TOT_EMPLOYEE
FROM MOCK_DATA;


-- Gender Wise Employee Count


SELECT GENDER,
COUNT(*) AS TOT_EMPLOYEE
FROM MOCK_DATA
GROUP BY GENDER;

------------------------------------

--Gender wise Emp Percentage

WITH GENDERWISE AS
(
SELECT GENDER,
COUNT(*) AS TOT_EMP
FROM  MOCK_DATA
GROUP BY gender

)
SELECT GENDER,
TOT_EMP*100.0/SUM(TOT_EMP)OVER() AS EMP_PERCENTAGE
FROM GENDERWISE;


-- AVERAGE PERFORMANCE SCORE


SELECT AVG(CAST(Performance_Score AS DECIMAL(10,2))) AS AVG_PER_SCORE
FROM MOCK_DATA;

--AVERAGE SALARY

SELECT SUM(Salary) AS AVG_SALARY
FROM MOCK_DATA;

--ATTRITION COUNT

SELECT 
SUM(CASE WHEN Attrition = 1 THEN 1 ELSE 0 END) AS ATTRITION_COUNT
FROM MOCK_DATA;

-- AVERAGE WORK HOURS

SELECT AVG(CAST(Work_Hour_Per_Month AS DECIMAL(10,2))) AS MONTHLY_AVG_WORK_HRS
FROM MOCK_DATA;


--AVERAGE WORK EXPERIENCE

WITH AVG_EXP AS (
    SELECT *,
    -- DATEDIFF ko FLOAT mein convert karke dino ke hisab se nikalein
    CAST(DATEDIFF(DAY, Joining_Date, GETDATE()) AS FLOAT) / 365 AS EXP_YEAR
    FROM MOCK_DATA
)
SELECT AVG(EXP_YEAR) AS AVG_EXP_YEAR FROM AVG_EXP;


--DEPARTMENTWISE EMP COUNT

SELECT Department,
COUNT(*) AS TOT_EMPLOYEE
FROM MOCK_DATA
GROUP BY Department;


-- TOTAL EMPLOYEE BY LOCATION

SELECT Location,
COUNT(*) AS TOT_EMPLOYEE 
FROM MOCK_DATA
GROUP BY LOCATION;


-- ATTRITION BY DEPARTMENT

SELECT Department,
SUM(CASE WHEN Attrition = 1 THEN 1 ELSE 0 END) AS ATTRITION
FROM MOCK_DATA
GROUP BY Department;


-- ATTRITION BY LOCATION
SELECT Location,
SUM(CASE WHEN Attrition = 1 THEN 1 ELSE 0 END) AS ATTRITION
FROM MOCK_DATA
GROUP BY Location;



-- SALARY DISTRIBUTION BY JOB ROLE

SELECT Job_Role,
ROUND(SUM(Salary),2) AS TOT_SALARY
FROM MOCK_DATA
GROUP BY Job_Role;

-- ATTENDANCE PERCENT BY DEPARTMENTS

SELECT Department,
ROUND(AVG(Attendence_Percent), 1) AS Avg_Attendance_Percent
FROM MOCK_DATA
GROUP BY Department;


-- Job Role Wise Min,Max and Avg Salary --

SELECT Job_Role,
MAX(SALARY) AS MAX_SAL,
MIN(SALARY) AS MIN_SAL,
AVG(SALARY) AS AVG_SAL
FROM MOCK_DATA
GROUP BY Job_Role;